# Generated by Django 5.1 on 2024-08-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('site_id', models.CharField(blank=True, max_length=50, null=True)),
                ('road', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryId', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='CategoryName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_birth', models.DateField()),
                ('user_avator', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spotimages',
            fields=[
                ('imageid', models.AutoField(db_column='ImageId', primary_key=True, serialize=False)),
                ('spotid', models.IntegerField(blank=True, db_column='SpotId', null=True)),
                ('imagetitle', models.CharField(blank=True, db_column='ImageTitle', max_length=300, null=True)),
                ('imagepath', models.CharField(blank=True, db_column='ImagePath', max_length=200, null=True)),
            ],
            options={
                'db_table': 'spotimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('spotid', models.AutoField(db_column='SpotId', primary_key=True, serialize=False)),
                ('categoryid', models.IntegerField(blank=True, db_column='CategoryId', null=True)),
                ('spottitle', models.CharField(blank=True, db_column='SpotTitle', max_length=50, null=True)),
                ('spotdescription', models.TextField(blank=True, db_column='SpotDescription', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('trafficinfo', models.CharField(blank=True, db_column='TrafficInfo', max_length=300, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=20, null=True)),
                ('opentime', models.CharField(blank=True, db_column='OpenTime', max_length=300, null=True)),
                ('contactphone', models.CharField(blank=True, db_column='ContactPhone', max_length=200, null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
            ],
            options={
                'db_table': 'spots',
                'managed': False,
            },
        ),
    ]
